### ISSUE TITLE
TypeError: 'LazyManifestIterator' object is not subscriptable

### ISSUE THREAD

**Issue by Zhang-Xiaoyi** [lifeiteng/vall-e#119]
I encounter this error when preparing aishell-1 dataset
2023-05-08 19:29:04 (prepare.sh:83:main) Stage 3: Prepare aishell train/dev/test
Traceback (most recent call last):
  File "***/anaconda3/envs/valle/bin/lhotse", line 8, in <module>
    sys.exit(cli())
  File "***/anaconda3/envs/valle/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "***/anaconda3/envs/valle/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "***/anaconda3/envs/valle/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "***/anaconda3/envs/valle/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "***/anaconda3/envs/valle/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "***/anaconda3/envs/valle/lib/python3.9/site-packages/lhotse/bin/modes/manipulation.py", line 231, in subset
    a_subset = any_set.subset(first=first, last=last, cut_ids=cids)
  File "***/anaconda3/envs/valle/lib/python3.9/site-packages/lhotse/cut/set.py", line 979, in subset
    return CutSet.from_cuts(self[cid] for cid in cut_ids)
  File "***/anaconda3/envs/valle/lib/python3.9/site-packages/lhotse/cut/set.py", line 275, in from_cuts
    return CutSet(cuts=index_by_id_and_check(cuts))
  File "***/anaconda3/envs/valle/lib/python3.9/site-packages/lhotse/utils.py", line 630, in index_by_id_and_check
    for m in manifests:
  File "***/anaconda3/envs/valle/lib/python3.9/site-packages/lhotse/cut/set.py", line 979, in <genexpr>
    return CutSet.from_cuts(self[cid] for cid in cut_ids)
  File "***/anaconda3/envs/valle/lib/python3.9/site-packages/lhotse/cut/set.py", line 2463, in __getitem__
    return self.cuts[cut_id_or_index]
TypeError: 'LazyManifestIterator' object is not subscriptable

**Comment by sty1992928** [comment]
update lhotse, pip install lhotse==1.14.0

**Comment by Zhang-Xiaoyi** [comment]
> update lhotse, pip install lhotse==1.14.0

cool. this works.

**Comment by Zhang-Xiaoyi** [comment]
solved

**Comment by friendmine** [comment]
cool. awesome
