### ISSUE TITLE
tokenizer.py error

### ISSUE THREAD

**Issue by tom1997** [lifeiteng/vall-e#145]
I tried to trained on aishell4, after prepare the dataset manifests
I run `python3 bin/tokenizer.py --dataset-parts "train_L train_S train_M test" --text-extractor "pypinyin_initials_finals" --audio-extractor Encodec --batch-duration 400 --prefix aishell4 --src-dir ../../../dataset/aishell4/manifects/ --output-dir data/tokenized`
And I got the following log
Computing features in batches:   0%|                                                                                                                        | 0/30 [00:00<?, ?it/s]0it [00:00, ?it/s]
Traceback (most recent call last):
  File "bin/tokenizer.py", line 263, in <module>
    main()
  File "bin/tokenizer.py", line 227, in main
    for c in tqdm(cut_set):
  File "/zhangyingxian/miniconda3/envs/valle/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
TypeError: 'NoneType' object is not iterable

I already re-install the least lhotse version, how could I solve it?

**Comment by sherryxie1** [comment]
manifests = read_manifests_if_cached(
        dataset_parts=dataset_parts,
        output_dir=args.src_dir,
        prefix=args.prefix,
        suffix=args.suffix,
        types=["recordings", "supervisions", "cuts"],
    ) 
maybe you can check your manifests first

**Comment by tom1997** [comment]
ok, I just print it 
{'train': {'recordings': CutSet(len=0) [underlying data type: <class 'dict'>], 'supervisions': CutSet(len=0) [underlying data type: <class 'dict'>]}, 'dev': {'recordings': CutSet(len=0) [underlying data type: <class 'dict'>], 'supervisions': CutSet(len=0) [underlying data type: <class 'dict'>]}, 'test': {'recordings': CutSet(len=0) [underlying data type: <class 'dict'>], 'supervisions': CutSet(len=0) [underlying data type: <class 'dict'>]}}
CutSet is null, it seems I need to re-generate the manifests file?

**Comment by tom1997** [comment]
> ```
> manifests = read_manifests_if_cached(
>     dataset_parts=dataset_parts,
>     output_dir=args.src_dir,
>     prefix=args.prefix,
>     suffix=args.suffix,
>     types=["recordings", "supervisions", "cuts"],
> ) 
> ```
> 
> maybe you can check your manifests first

ok, I just print it 

```{'train': {'recordings': CutSet(len=0) [underlying data type: <class 'dict'>], 'supervisions': CutSet(len=0) [underlying data type: <class 'dict'>]}, 'dev': {'recordings': CutSet(len=0) [underlying data type: <class 'dict'>], 'supervisions': CutSet(len=0) [underlying data type: <class 'dict'>]}, 'test': {'recordings': CutSet(len=0) [underlying data type: <class 'dict'>], 'supervisions': CutSet(len=0) [underlying data type: <class 'dict'>]}```

CutSet is null. And I try re-generate again by prepare.sh, it remain the same.

**Comment by liuchaofei** [comment]
> I solved it by setting the right path of dataset, refer to lhotse

can you explain it more detail

**Comment by tom1997** [comment]
You can see lhotse[https://github.com/lhotse-speech/lhotse/tree/master/lhotse/recipes)] readme file, and make sure the prepare.sh path match to the manifests file.
