### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by danfouer** [lifeiteng/vall-e#149]
### when I was following https://github.com/lifeiteng/vall-e/blob/main/egs/aishell1/README.md
(VALLE) danfouer@GPU1070:~/Videos/7Github/valle/egs/aishell1$ bash prepare.sh --stage -1 --stop_stage 3
2023-07-17 06:09:32 (prepare.sh:42:main) dl_dir: /home/danfouer/Videos/7Github/valle/egs/aishell1/download
2023-07-17 06:09:32 (prepare.sh:43:main) Stage 0: Download data
2023-07-17 06:09:32 (prepare.sh:56:main) Stage 1: Prepare aishell manifest
2023-07-17 06:09:32 (prepare.sh:68:main) Stage 2: Tokenize/Fbank aishell
2023-07-17 06:09:38,630 INFO [tokenizer.py:154] dataset_parts: ['train', '', 'dev', '', 'test'] manifests 3
2023-07-17 06:09:38,709 INFO [tokenizer.py:161] Processing partition: train CUDA: True
Computing features in batches: 0it [00:00, ?it/s]
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "bin/tokenizer.py", line 262, in <module>
    main()
  File "bin/tokenizer.py", line 226, in main
    for c in tqdm(cut_set):
  File "/home/danfouer/.local/lib/python3.8/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
TypeError: 'NoneType' object is not iterable
### my system is ubuntu22.04, GPU is 1070
pip3 install torch torchvision torchaudio
#Successfully installed torch-1.10.2 torchaudio-0.10.2 typing-extensions-4.7.1
pip3 install torchmetrics
#Successfully installed lightning-utilities-0.9.0 torchmetrics-1.0.1
pip3 install librosa
#Successfully installed lazy-loader-0.3 librosa-0.10.0.post2 msgpack-1.0.5 soundfile-0.12.1 soxr-0.3.5

**Comment by lifeiteng** [comment]
看下 data/manifests 下数据对不对

**Comment by danfouer** [comment]
![image](https://github.com/lifeiteng/vall-e/assets/4875770/a5495eb5-f933-4c44-a8b5-c7acd9930c6b)

would you please send the data/manifests 下数据 to 308502572@qq.com
