### ISSUE TITLE
No such attribute 'prefix_mode'

### ISSUE THREAD

**Issue by bensonbs** [lifeiteng/vall-e#172]
```
root@afdda5ba48ca:/workspace/vall-e/valle# python3 bin/infer.py --output-dir infer/demos \
>     --checkpoint /workspace/vall-e/epoch-100.pt \
>     --text-prompts "KNOT one point one five miles per hour." \
>     --audio-prompts /workspace/vall-e/prompts/js-209.wav \
>     --text "這裡是美的沉思我是蔣勳" \
> 
```

```
Traceback (most recent call last):
  File "/workspace/vall-e/valle/bin/infer.py", line 282, in <module>
    main()
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/vall-e/valle/bin/infer.py", line 155, in main
    model, text_tokens = load_model(args.checkpoint, device)
  File "/workspace/vall-e/valle/bin/infer.py", line 133, in load_model
    model = get_model(args)
  File "/workspace/valle/valle/models/__init__.py", line 119, in get_model
    prefix_mode=params.prefix_mode,
  File "/workspace/icefall/icefall/utils.py", line 167, in __getattr__
    raise AttributeError(f"No such attribute '{key}'")
AttributeError: No such attribute 'prefix_mode'
```

**Comment by wsstriving** [comment]
May I know how you fix this problem?
