### ISSUE TITLE
Model not improving

### ISSUE THREAD

**Issue by apzl** [lifeiteng/vall-e#27]
Trained the vall-e model for 10 epochs using LibriTTS dataset and the outputs are not improving. Here's the output after 10th epoch.

![vall-e-out_10.wav](http://drive.google.com/uc?export=view&id=1pXXeM7h1vhmVkVF-SwyZjbqutfvbv_7q)

**Comment by lifeiteng** [comment]
@apzl  `git pull origin main`
The full model can be trained on a single GPU! https://github.com/lifeiteng/vall-e/blob/main/egs/libritts/README.md#training

<img width="1322" alt="截屏2023-02-18 21 00 15" src="https://user-images.githubusercontent.com/3107839/219867128-bfb07dc5-cede-478d-b3c8-71cc9f089b7d.png">

**Comment by apzl** [comment]
when training with `use-fp16=true`, getting this error.

```
Traceback (most recent call last):
  File "bin/trainer.py", line 979, in <module>
    main()
  File "bin/trainer.py", line 972, in main
    run(rank=0, world_size=1, args=args)
  File "bin/trainer.py", line 868, in run
    train_one_epoch(
  File "bin/trainer.py", line 654, in train_one_epoch
    raise RuntimeError(
RuntimeError: grad_scale is too small, exiting: 2.7755575615628914e-17
```
command used to start training is:
`bash run.sh --stage 4 --stop-stage 4 --num-decoder-layers 12 --max-duration 24 --use-fp16 true`

**Comment by lifeiteng** [comment]
@apzl I have add Top10 Accuracy Metric and tuning AdamW & learning_rate https://github.com/lifeiteng/vall-e/pull/31

AR Top10 accuracy is greatly improved.

**Comment by lifeiteng** [comment]
If AR decoder Top10 accuracy > 40%, I think the synthesised wav will be accurate and clean.
