### ISSUE TITLE
Error during Prepare Dataset LJSpeech

### ISSUE THREAD

**Issue by kin0303** [lifeiteng/vall-e#48]
I want to do a training with LJSpeech dataset and get an error like this when the preparation:
```
bash run.sh --stage -1 --stop-stage 3     --audio_extractor "Fbank"     --audio_feats_dir data/fbank
```

```
2023-03-06 13:20:42 (run.sh:45:main) dl_dir: /media/7A76476176471D6F/VALL-E/valle/egs/ljspeech/download
2023-03-06 13:20:42 (run.sh:48:main) Stage 0: Download data
2023-03-06 13:20:42 (run.sh:61:main) Stage 1: Prepare LJSpeech manifest
2023-03-06 13:20:42 (run.sh:73:main) Stage 2: Split LJSpeech
2023-03-06 13:20:42 (run.sh:94:main) Stage 3: Fbank LJSpeech
2023-03-06 13:21:15,837 INFO [tokenizer.py:140] Processing partition: train CUDA: True
Extracting and storing features: 100%|██| 12500/12500 [10:26<00:00, 19.95it/s]
  0%|                                               | 0/12500 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "bin/tokenizer.py", line 201, in <module>
    main()
  File "bin/tokenizer.py", line 173, in main
    text = c.supervisions[0].custom["normalized_text"]
TypeError: 'NoneType' object is not subscriptable
```
How do I solve this error?

**Comment by lifeiteng** [comment]
You should update lhoste

https://github.com/lifeiteng/vall-e/tree/main/egs/ljspeech#install-deps

**Comment by baochi0212** [comment]
Has this problem been solved ?, I still encounter it with lhotse version 1.16.0
