### ISSUE TITLE
AttributeError: 'CutSet' object has no attribute 'find'

### ISSUE THREAD

**Issue by sankar-mukherjee** [lifeiteng/vall-e#79]
Traceback (most recent call last):
File "/workspaces/vall-e/egs/libritts/bin/tokenizer.py", line 204, in
main()
File "/workspaces/vall-e/egs/libritts/bin/tokenizer.py", line 146, in main
cut_set = CutSet.from_manifests(
File "/root/miniconda3/envs/valle/lib/python3.10/site-packages/lhotse/cut/set.py", line 317, in from_manifests
return create_cut_set_eager(
File "/root/miniconda3/envs/valle/lib/python3.10/site-packages/lhotse/cut/set.py", line 2937, in create_cut_set_eager
supervisions.find(
AttributeError: 'CutSet' object has no attribute 'find'

getting this error when I try to run
bash prepare.sh --stage -1 --stop-stage 3

**Comment by lifeiteng** [comment]
Is it the dataset in egs/?

**Comment by sankar-mukherjee** [comment]
I solved this issue here
https://github.com/lhotse-speech/lhotse/issues/1024
