### ISSUE TITLE
Error: Prepare LibriTTS train/dev/test 

### ISSUE THREAD

**Issue by do-web** [lifeiteng/vall-e#9]
```
Stage 3: Prepare LibriTTS train/dev/test
Traceback (most recent call last):
  File "/opt/conda/envs/tts/bin/lhotse", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/envs/tts/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/tts/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/tts/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/tts/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/tts/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/envs/tts/lib/python3.10/site-packages/lhotse/bin/modes/manipulation.py", line 251, in combine
    data_set = combine_manifests(*[load_manifest_lazy_or_eager(m) for m in manifests])
  File "/opt/conda/envs/tts/lib/python3.10/site-packages/lhotse/manipulation.py", line 30, in combine
    return reduce(add, manifests)
  File "/opt/conda/envs/tts/lib/python3.10/site-packages/lhotse/lazy.py", line 123, in __add__
    return cls(LazyIteratorChain(self.data, other.data))
AttributeError: 'NoneType' object has no attribute 'data'
```

**Comment by lifeiteng** [comment]
make sure stage 2 is ok
