### ISSUE TITLE
LibriTTS Preprocessing Error: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by stanleyshly** [lifeiteng/vall-e#92]
I've noticed an error in the tokenization process only when running the 100, 360, and 500 split of LibriTTS, but not when processing dev-clean.tar.gz, dev-other.tar.gz, test-clean.tar.gz, and test-other.tar.gz splits. 

Here is the error:
```
2023-04-16 16:33:14 (prepare.sh:42:main) dl_dir: /home/workstation/Desktop/vall-e/egs/libritts/download
2023-04-16 16:33:14 (prepare.sh:43:main) Stage 0: Download data
Downloading train-clean-100.tar.gz: 7.19GB [07:44, 16.6MB/s]                                                                                  
Downloading LibriTTS parts: 100%|███████████████████████████████████████████████████████████████████████████████| 1/1 [09:56<00:00, 596.42s/it]
2023-04-16 16:43:13 (prepare.sh:57:main) Stage 1: Prepare LibriTTS manifest
2023-04-16 16:43:13 (prepare.sh:69:main) Stage 2: Tokenize/Fbank LibriTTS
2023-04-16 16:43:18,722 INFO [tokenizer.py:151] Processing partition: train-clean-100 CUDA: True
Computing features in batches: 0it [00:00, ?it/s]
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/workstation/Desktop/vall-e/egs/libritts/bin/tokenizer.py", line 238, in <module>
    main()
  File "/home/workstation/Desktop/vall-e/egs/libritts/bin/tokenizer.py", line 203, in main
    for c in tqdm(cut_set):
  File "/home/workstation/.local/lib/python3.10/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
TypeError: 'NoneType' object is not iterable
```

Any idea where this error is coming up? Not sure why it is only happening for the 100, 360, and 500 splits.

**Comment by egornya** [comment]
> @stanleyshly update lhotse
> 
> #34

Hi, I'm having a similar issue with the latest lhotse installed, don't know what to do really.

`100%|████████████████████████████████████████████████████████| 116500/116500 [01:29<00:00, 1300.74it/s]
2023-05-25 20:19:34,433 INFO [tokenizer.py:161] Processing partition: train-other-500 CUDA: True
Computing features in batches: 0it [00:00, ?it/s]
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/root/valle/egs/libritts/bin/tokenizer.py", line 262, in <module>
    main()
  File "/root/valle/egs/libritts/bin/tokenizer.py", line 226, in main
    for c in tqdm(cut_set):
  File "/usr/local/lib/python3.10/dist-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
TypeError: 'NoneType' object is not iterable`

**Comment by stanleyshly** [comment]
Try downloading and reinstalling everything. If that doesn't work, delete your LibriTTS files and do a clean download.
